Mini2p2023
kavli-ntnu/MINI2P_toolbox pull request #24
Opened 2023-08-16 13:50 UTC by marinesrj

add protocol P5-Performance Tests and updated shopping list with new item.

2023-08-16 21:28 UTC, WeijianZong approved these changes

2023-08-16 21:28 UTC, WeijianZong commented
Approve

2023-08-17 07:18 UTC, simon-ball requested changes
Check the links in the readme file first. Since you keep renaming files when you edit them, you need to fix the links that point to them as well. You can avoid this by sticking to a (undated) naming style and leaving file names unchanged when editing. 

Bear in mind that you have a mixture of link styles used. Relative pointers will update themselves, so it's not a problem that they currently resolve tot he `mini2p2023` branch. Any absolute links need to first be tested in the development branch, and then have the branch pointer updated to `main` for the PR (because the development branch will then go away, and pointers to that branch would fail)

At least, the current links need to be reveiwed, and you should check and test the others. 

* 2.a) P1
* 2.b) P2
* 2.c) P3 (also formatting)

This is a relative link:
```
## Contents: 

1) [Hardware](Hardware)
```
Which is usually pretty safe, but Github will only resolve it for directories and text files


This is an absolute link
```
 [Protocols overview](https://github.com/kavli-ntnu/MINI2P_toolbox/blob/main/Protocols/Protocols%20Overview%20.pdf) including video-tutorial links.
 ```
 It points specically to the latest state of a file in the `main` branch - and it doesn't currently work at all, probably because the file it points to was renamed in the last PR, and I didn't catch that error when I fixed a few others.

2023-09-05 12:22 UTC, simon-ball approved these changes

2023-09-05 12:22 UTC, merged